// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxnydksqgodxmeijjrza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bnlka3NxZ29keG1laWpqcnphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTkxNzMsImV4cCI6MjA3NDUzNTE3M30.Zx-kn52H-fiexYaQJxDKblyxO1Ai3Cg7VU0jycvZ04o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});